In [1]:
import tensorflow as tf

In [8]:
ds = tf.data.Dataset.from_tensor_slices(tf.random.categorical(tf.math.log([[0.5, 0.5]]), [10, 32, 32, 1]))

InvalidArgumentError: num_samples should be a scalar, got shape [4] [Op:Multinomial]

In [7]:
for d in ds:
    print(d.numpy())

[0 1 1 0 1 1 1 0 1 0]


In [9]:
import numpy as np

In [10]:
data = np.random.choice([0, 1], size=(10, 32, 32, 1), p=[0.5, 0.5])

In [23]:
ds = tf.data.Dataset.from_tensor_slices(data)

In [18]:
print(d[10].numpy())

[[1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]]


In [21]:
data[1]

array([[[0],
        [0],
        [1],
        ...,
        [0],
        [0],
        [0]],

       [[1],
        [0],
        [0],
        ...,
        [0],
        [0],
        [1]],

       [[0],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       ...,

       [[1],
        [1],
        [0],
        ...,
        [1],
        [1],
        [0]],

       [[1],
        [0],
        [0],
        ...,
        [0],
        [1],
        [0]],

       [[1],
        [0],
        [1],
        ...,
        [1],
        [1],
        [1]]])

In [26]:
ds = tf.data.Dataset.from_tensor_slices([[[1, 1], [1, 1]], [[2, 2], [2, 2]], [[3, 3], [3, 3]], [[4, 4], [4, 4]]])
for d in ds:
    print(d.numpy())

[[1 1]
 [1 1]]
[[2 2]
 [2 2]]
[[3 3]
 [3 3]]
[[4 4]
 [4 4]]


In [27]:
print(ds[0].numpy())

TypeError: 'TensorSliceDataset' object is not subscriptable

In [28]:
ds.batch(1)

<BatchDataset element_spec=TensorSpec(shape=(None, 2, 2), dtype=tf.int32, name=None)>

In [29]:
for d in ds.take(4):
    print(d.numpy())

[[1 1]
 [1 1]]
[[2 2]
 [2 2]]
[[3 3]
 [3 3]]
[[4 4]
 [4 4]]
